## 仮想環境: stardist binary2hdf5.pyが同じ階層にあるか確認！

# Please install h5py if it has not been installed

In [1]:
from binary2hdf5 import read_hdf5_at_t, read_virtual_hdf5
import os
import tifffile as tiff
import h5py
import time
import numpy as np

# Read all frames of HDF5 and write into Tiff file
- `hdf5_path=`: Path to the hdf5 files

You must enter the number of volumes.  In this part, hdf5_file is generated in the same directory of hdf5_file.

In [ ]:

hdf5_path=r"C:\adamshch-naomi_sim-65718ae7abb7\adamshch-naomi_sim-65718ae7abb7\code\4d_data.h5"# tif形式に保存したいhdf5ファイルのパスを指定してください

with h5py.File(hdf5_path, 'r') as file:
    t0 = time.time()
    array = file['default']
    volumes = array.shape[0]
    print(volumes)
basename_without_ext = os.path.splitext(os.path.basename(hdf5_path))[0]
dirname = os.path.dirname(hdf5_path)
output_path = os.path.join(dirname,"tiff_output","raw")
print(output_path)

if not os.path.exists(output_path):
    os.makedirs(output_path)

for frame in range(volumes):

    image = read_virtual_hdf5(hdf5_path=hdf5_path, t=frame+1) 
    #image = np.transpose(image, (1, 0, 2, 3,))
    #image = np.transpose(image, (1, 0, 2, 3,))
    image = image[0]
    file_name = f"image_raw_t={frame}.tif"
    output_path2 = os.path.join(output_path, file_name)

    #tiff.imsave(file_path, three_dimensional_image)
    tiff.imwrite(output_path2, image,imagej=True, metadata={'axes': 'ZYX'}, compression ='zlib') # volumeを保存する


10
C:\adamshch-naomi_sim-65718ae7abb7\adamshch-naomi_sim-65718ae7abb7\code\tiff_output\raw


ValueError: 5 indexing arguments for 4 dimensions

# Read selected frames of HDF5 and write into tifffile

In [2]:
t_start =365
#はじめたいvolumeを指定、t=1スタート
volume_number= 107#tiff化したい数、MAなら2,rawなら２１
for frame in range(t_start, t_start+volume_number):   
    frame = frame # tifファイル化したいボリュームを指定してください,t=1スタートです

    hdf5_path= r"P:\Tardigrade\Tardigrada_mukumoto\orig\20240902-161310kumamushi_raw_gzip.h5"
    # tif形式に保存したいhdf5ファイルのパスを指定してください


    image = read_hdf5_at_t(hdf5_path=hdf5_path, t=frame) # tif形式に保存したいhdf5ファイルのパスを指定してください
    print(image)

    for channels in range(2):

        #output_folder = f"output_ch{channels+1}"
        dirname = os.path.dirname(hdf5_path)


        output_path = os.path.join(dirname,"raw_tiff_output","ch="+str(channels+1))
        #output_path = os.path.join(dirname,"tiff_output")
        if not os.path.exists(output_path):
            os.makedirs(output_path)

        #for j in range(image.shape[1]):
            # 4次元データから2次元のデータを取得
        three_dimensional_image = image[channels]


            # PILのImageオブジェクトに変換
        #pil_image = Image.fromarray(three_dimensional_image)

            # TIFFファイルとして保存
        file_name = f"image_ch{channels+1}_t={frame}.tif"
        file_path = os.path.join(output_path, file_name)
        #pil_image.save(file_path)
        tiff.imsave(file_path, three_dimensional_image)


Read images at t=365 takes 0.799s
Image shape (vols, channels, z, y, x): (665, 2, 118, 707, 824)
[[[[  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...  88 101   0]
   ...
   [  0   0   0 ...  87 102   0]
   [  0   0   0 ...  88 108   0]
   [  0   0   0 ...  96 116   0]]

  [[  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ... 101   0   0]
   ...
   [  0   0   0 ... 100   0   0]
   [  0   0   0 ... 100   0   0]
   [  0   0   0 ... 106   0   0]]

  [[  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   ...
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]]

  ...

  [[  0  99 103 ...   0   0   0]
   [  0 111 118 ...   0   0   0]
   [  0 102 108 ...   0   0   0]
   ...
   [  0 117 130 ...   0   0   0]
   [  0 107 120 ...   0   0   0]
   [  0  99 108 ...   0   0   0]]

  [[111 103  83 ...   0   0   0]
   [107 108  93 ...   0   0   0]
  

C:\Users\mikamilab\AppData\Local\Temp\ipykernel_13884\2967457696.py:37: DeprecationWarning: <tifffile.imsave> is deprecated. Use tifffile.imwrite
  tiff.imsave(file_path, three_dimensional_image)


Read images at t=366 takes 0.767s
Image shape (vols, channels, z, y, x): (665, 2, 118, 707, 824)
[[[[  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...  88  96   0]
   ...
   [  0   0   0 ...  85  99   0]
   [  0   0   0 ...  93  99   0]
   [  0   0   0 ...  88 107   0]]

  [[  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ... 101   0   0]
   ...
   [  0   0   0 ... 101   0   0]
   [  0   0   0 ... 114   0   0]
   [  0   0   0 ...  99   0   0]]

  [[  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   ...
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]
   [  0   0   0 ...   0   0   0]]

  ...

  [[  0  96 104 ...   0   0   0]
   [  0  99 102 ...   0   0   0]
   [  0 105 114 ...   0   0   0]
   ...
   [  0 114 101 ...   0   0   0]
   [  0 108 113 ...   0   0   0]
   [  0 100 111 ...   0   0   0]]

  [[115 101  80 ...   0   0   0]
   [104 100  82 ...   0   0   0]
  

# Show the loaded image projected to x-y plane

In [ ]:
import matplotlib.pyplot as plt
print("Channel 1, max projection")
plt.figure(figsize=(20,10))
plt.imshow(image[0,...].max(axis=0))
plt.pause(0.1)
print("Channel 2, max projection")
plt.figure(figsize=(20,10))
plt.imshow(image[1,...].max(axis=0))

In [ ]:
import h5py
import numpy as np
import os

# === 入力ファイルと出力ファイルのパス ===
input_hdf5_path = r"\\4-307-km\p\Tardigrade\Tardigrada_mukumoto\orig\raw_t=0~225\raw_t=1~225.h5"
output_hdf5_part1 = r"H:\kumamushi-new\split_part1_t000-112.h5"
output_hdf5_part2 = r"H:\kumamushi-new\split_part1_t113-224.h5"

# 分割範囲
split_ranges = {
    output_hdf5_part1: (0, 113),    # t = 0~112
    output_hdf5_part2: (113, 225)   # t = 113~224
}

# データを1フレームずつコピー
with h5py.File(input_hdf5_path, 'r') as f_in:
    dataset_name = list(f_in.keys())[0]
    data = f_in[dataset_name]
    z, c, t_total, y, x = data.shape
    dtype = data.dtype

    for out_path, (t_start, t_end) in split_ranges.items():
        t_len = t_end - t_start
        print(f"Writing {out_path} ...")

        with h5py.File(out_path, 'w') as f_out:
            dset = f_out.create_dataset(
                dataset_name,
                shape=(z, c, t_len, y, x),
                dtype=dtype,
                chunks=(z, c, 1, y, x)  # 時間方向1ボリュームごとにチャンク化
    
        
            )

            for i, t in enumerate(range(t_start, t_end)):
                print(f"  Copying t={t} → t'={i}")
                dset[:, :, i, :, :] = data[:, :, t, :, :]

Writing H:\kumamushi-new\split_part1_t000-112.h5 ...
  Copying t=0 → t'=0
  Copying t=1 → t'=1
  Copying t=2 → t'=2
  Copying t=3 → t'=3
  Copying t=4 → t'=4
